version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    ports:
      - "8080:80"  # Mapeia a porta 80 do container para a porta 8080 no host
    volumes:
      - ./src:/var/www/html  # Mapeia o diretório local 'src' para o container
      - ./vendor:/var/www/html/vendor  # Mapeia a pasta vendor para o container (para manter as dependências do Composer)
      - ./composer.json:/var/www/html/composer.json  # Mapeia o arquivo composer.json para o container
    networks:
      - app-network
    depends_on:
      - mysql
    command: bash -c "composer install && php -S 0.0.0.0:80 -t /var/www/html"  # Instala as dependências do Composer e depois inicia o servidor PHP embutido
    
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Mapeia a porta do MySQL no container para a do host
    volumes:
      - db_data:/var/lib/mysql  # Persistência de dados do MySQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:  # Volume nomeado para persistência de dados do MySQL